name: kosher_dart
description: This Plugin for a specialized calendar that can calculate different astronomical times including sunrise and sunset and
  Jewish zmanim or religious times for prayers and other Jewish religious duties.
version: 2.0.0
author: Yakir Benin
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.beninsapps.kosher_dart
    pluginClass: KosherDartPlugin
