name: kosher_dart
description: This Plugin for a specialized calendar that can calculate different
  astronomical times for Jewish zmanim or religious times for prayers and other Jewish religious duties.
version: 2.0.2
homepage:  https://github.com/yakir8/kosher_dart
#author: Yakir Benin

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.12.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
#  intl: ^0.16.1
  vector_math: ^2.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      androidPackage: com.beninsapps.kosher_dart
      pluginClass: KosherDartPlugin